### ISSUE TITLE
plz update gradle 7.6 version

### ISSUE THREAD

**Issue by kbs-it** [lancard/android-cordova#3]
Gradle 7.6 version has been released. If possible, can you update the docker hub?

**Comment by lancard** [comment]
> Gradle 7.6 version has been released. If possible, can you update the docker hub?

ok got it stby.

**Comment by lancard** [comment]
it will be update in 5min. thanks for information.

**Comment by lancard** [comment]
plz write issue in https://github.com/lancard/cordova-android-docker  and PR plz
